/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImageJPanel.java
 *
 * Created on 12 Nov, 2009, 11:55:29 AM
 */
package gui;

import java.awt.AlphaComposite;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import java.awt.Composite;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.Stroke;
import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;

/**
 *
 * @author gsk
 */
public class ImageFrameJPanel extends javax.swing.JPanel {

    String img = "";
    BufferedImage image = null;

    /**
     * Creates new form ImageJPanel
     */
    public ImageFrameJPanel() {

        initComponents();
    }

    @Override
    public void paintComponent(Graphics g1) {
        Graphics2D g = (Graphics2D) g1;
        if (!img.equals("")) {
            try {
                image = ImageIO.read(new File(img));
            } catch (IOException ex) {
                // handle exception...
            }
            g.drawImage(image, 0, 0, getWidth(), getHeight(), null); // see javadoc for more info on the parameters            

            float dash1[] = {0.1f};
            BasicStroke dashed
                    = new BasicStroke(1.0f,
                            BasicStroke.JOIN_ROUND,
                            BasicStroke.JOIN_MITER,
                            1.0f, dash1, 0.0f);
            g.setStroke(dashed);
            g.setColor(Color.red);
            //   image.getGraphics().setColor(Color.red);
            g.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER,
                    0.1f));
            //   g.drawLine(0, getHeight() / 2, getWidth(), getHeight() / 2);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
