/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * loginJFrame1.java
 *
 * Created on 17 Mar, 2009, 8:33:50 PM
 */
package gui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

public class loginJFrame1 extends javax.swing.JInternalFrame {

    MainFrame obj = null;

    /**
     * Creates new form loginJFrame1
     */
    public loginJFrame1(MainFrame obj) {
        this.obj = obj;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jDesktopPane1.setBackground(new java.awt.Color(227, 227, 238));

        jLabel1.setText("Username");
        jLabel1.setBounds(70, 40, 90, 14);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setText("Password");
        jLabel2.setBounds(70, 90, 90, 14);
        jDesktopPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jTextField1.setBounds(170, 40, 180, 20);
        jDesktopPane1.add(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPasswordField1.setBounds(170, 90, 180, 20);
        jDesktopPane1.add(jPasswordField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(80, 140, 270, 23);
        jDesktopPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jTextField1.getText() == null || (jTextField1.getText() != null && jTextField1.getText().equals(""))) {
            JOptionPane.showMessageDialog(jDesktopPane1, "Please Enter the userrname");
        } else if (jPasswordField1.getText() == null || (jPasswordField1.getText() != null && jPasswordField1.getText().equals(""))) {
            JOptionPane.showMessageDialog(jDesktopPane1, "Please Enter the Password");
        } else {
            try {
                if (!jTextField1.getText().equals("admin") && !jPasswordField1.getText().equals("admin")) {
                    JOptionPane.showMessageDialog(jDesktopPane1, "Please Enter the Correct userrname/Password");

                } else {
                    obj.loginSuccess();
                    this.hide();
                    this.dispose();
//                    NewJFrame.main(new String[]{});
                    this.dispose();
                }
            } catch (Exception ex) {
                Logger.getLogger(loginJFrame1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
