/*
 * MainFrame.java
 *
 * Created on July 22, 2009, 12:45 PM
 */
package gui;

import algo.BarChart3D;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author Administrator
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        String lnfName = "de.javasoft.plaf.synthetica.SyntheticaStandardLookAndFeel";

        initComponents();
        //loginOut();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Algorithms for Learning in Cooperative Multiagent Systems");
        setBackground(new java.awt.Color(252, 240, 215));
        setState(1);

        jMenu1.setText("Login");

        jMenuItem1.setText("Sign In");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Sign Out");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator1);

        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Agent");

        jMenuItem8.setText("Graph Clean");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem7.setText("Create Agent");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Q-Lerning");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem11.setText("Q-Learning Lamda");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem5.setText("Sarsa - Learning");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem10.setText("SarsaLamda - Learning");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem6.setText("Cooperative Q Learning  Algorithm ");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem12.setText("Cooperative Sarsa  Learning Algorithm ");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuItem13.setText("Cooperative Q Learning Lamda Algorithm ");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem13);

        jMenuItem14.setText("Cooperative Sarsa Lamda  Learning Algorithm ");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem14);

        jMenuItem9.setText("Graph ");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
        // Get the screen dimensions.
        java.awt.Dimension screen = tk.getScreenSize();
        QLJInternalFrame f = new QLJInternalFrame();
        int fw = (int) (screen.getWidth());
        int fh = (int) (screen.getWidth());
        java.awt.Dimension fs = f.getSize();
        int lx = (int) (screen.getWidth() / 2 - fs.getWidth() / 2);
        int ly = (int) (screen.getHeight() / 2 - fs.getHeight() / 2);
        f.setLocation(lx, ly);
        jDesktopPane1.add(f, javax.swing.JDesktopPane.CENTER_ALIGNMENT);
        f.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        //jDesktopPane1.setVisible(false)
        JInternalFrame[] frames = jDesktopPane1.getAllFrames();
        for (int i = 0; i < frames.length; i++) {
            frames[i].dispose();
        }
        loginOut();

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        dispose();
//        VideoOption V = new VideoOption();
//        java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
//        java.awt.Dimension screen = tk.getScreenSize();
//        int fw = (int) (screen.getWidth());
//        int fh = (int) (screen.getWidth());
//        java.awt.Dimension fs = V.getSize();
//        int lx = (int) (screen.getWidth() / 2 - fs.getWidth() / 2);
//        int ly = (int) (screen.getHeight() / 2 - fs.getHeight() / 2);
//        V.setLocation(lx, ly);
//        V.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        showLogin();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
        // Get the screen dimensions.
        java.awt.Dimension screen = tk.getScreenSize();
        RandomJInternalFrame f = new RandomJInternalFrame();
        int fw = (int) (screen.getWidth());
        int fh = (int) (screen.getWidth());
        java.awt.Dimension fs = f.getSize();
        int lx = (int) (screen.getWidth() / 2 - fs.getWidth() / 2);
        int ly = (int) (screen.getHeight() / 2 - fs.getHeight() / 2);
        f.setLocation(lx, ly);
        jDesktopPane1.add(f, javax.swing.JDesktopPane.CENTER_ALIGNMENT);
        f.show();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:

        java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
        // Get the screen dimensions.
        java.awt.Dimension screen = tk.getScreenSize();
        QLJInternalFrame2 f = new QLJInternalFrame2();
        int fw = (int) (screen.getWidth());
        int fh = (int) (screen.getWidth());
        java.awt.Dimension fs = f.getSize();
        int lx = (int) (screen.getWidth() / 2 - fs.getWidth() / 2);
        int ly = (int) (screen.getHeight() / 2 - fs.getHeight() / 2);
        f.setLocation(lx, ly);
        jDesktopPane1.add(f, javax.swing.JDesktopPane.CENTER_ALIGNMENT);
        f.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
        // Get the screen dimensions.
        java.awt.Dimension screen = tk.getScreenSize();
        QCSLJInternalFrame4 f = new QCSLJInternalFrame4(0);
        int fw = (int) (screen.getWidth());
        int fh = (int) (screen.getWidth());
        java.awt.Dimension fs = f.getSize();
        int lx = (int) (screen.getWidth() / 2 - fs.getWidth() / 2);
        int ly = (int) (screen.getHeight() / 2 - fs.getHeight() / 2);
        f.setLocation(lx, ly);
        jDesktopPane1.add(f, javax.swing.JDesktopPane.CENTER_ALIGNMENT);
        f.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        FileWriter fr = null;
        try {
            fr = new FileWriter(new File("graph.txt"));
            JOptionPane.showMessageDialog(rootPane, "Graph is Clean");
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fr.close();
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
        // Get the screen dimensions.
        java.awt.Dimension screen = tk.getScreenSize();
        GRaphJInternalFrame f = new GRaphJInternalFrame();
        int fw = (int) (screen.getWidth());
        int fh = (int) (screen.getWidth());
        java.awt.Dimension fs = f.getSize();
        int lx = (int) (screen.getWidth() / 2 - fs.getWidth() / 2);
        int ly = (int) (screen.getHeight() / 2 - fs.getHeight() / 2);
        f.setLocation(lx, ly);
        jDesktopPane1.add(f, javax.swing.JDesktopPane.CENTER_ALIGNMENT);
        f.show();

    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
        // Get the screen dimensions.
        java.awt.Dimension screen = tk.getScreenSize();
        QLJInternalFrame3 f = new QLJInternalFrame3();
        int fw = (int) (screen.getWidth());
        int fh = (int) (screen.getWidth());
        java.awt.Dimension fs = f.getSize();
        int lx = (int) (screen.getWidth() / 2 - fs.getWidth() / 2);
        int ly = (int) (screen.getHeight() / 2 - fs.getHeight() / 2);
        f.setLocation(lx, ly);
        jDesktopPane1.add(f, javax.swing.JDesktopPane.CENTER_ALIGNMENT);
        f.show();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
        // Get the screen dimensions.
        java.awt.Dimension screen = tk.getScreenSize();
        QLJInternalFrame4 f = new QLJInternalFrame4();
        int fw = (int) (screen.getWidth());
        int fh = (int) (screen.getWidth());
        java.awt.Dimension fs = f.getSize();
        int lx = (int) (screen.getWidth() / 2 - fs.getWidth() / 2);
        int ly = (int) (screen.getHeight() / 2 - fs.getHeight() / 2);
        f.setLocation(lx, ly);
        jDesktopPane1.add(f, javax.swing.JDesktopPane.CENTER_ALIGNMENT);
        f.show();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
        // Get the screen dimensions.
        java.awt.Dimension screen = tk.getScreenSize();
        QCSLJInternalFrame4 f = new QCSLJInternalFrame4(1);
        int fw = (int) (screen.getWidth());
        int fh = (int) (screen.getWidth());
        java.awt.Dimension fs = f.getSize();
        int lx = (int) (screen.getWidth() / 2 - fs.getWidth() / 2);
        int ly = (int) (screen.getHeight() / 2 - fs.getHeight() / 2);
        f.setLocation(lx, ly);
        jDesktopPane1.add(f, javax.swing.JDesktopPane.CENTER_ALIGNMENT);
        f.show();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
        // Get the screen dimensions.
        java.awt.Dimension screen = tk.getScreenSize();
        QCSLJInternalFrame4 f = new QCSLJInternalFrame4(2);
        int fw = (int) (screen.getWidth());
        int fh = (int) (screen.getWidth());
        java.awt.Dimension fs = f.getSize();
        int lx = (int) (screen.getWidth() / 2 - fs.getWidth() / 2);
        int ly = (int) (screen.getHeight() / 2 - fs.getHeight() / 2);
        f.setLocation(lx, ly);
        jDesktopPane1.add(f, javax.swing.JDesktopPane.CENTER_ALIGNMENT);
        f.show();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:

        java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
        // Get the screen dimensions.
        java.awt.Dimension screen = tk.getScreenSize();
        QCSLJInternalFrame4 f = new QCSLJInternalFrame4(3);
        int fw = (int) (screen.getWidth());
        int fh = (int) (screen.getWidth());
        java.awt.Dimension fs = f.getSize();
        int lx = (int) (screen.getWidth() / 2 - fs.getWidth() / 2);
        int ly = (int) (screen.getHeight() / 2 - fs.getHeight() / 2);
        f.setLocation(lx, ly);
        jDesktopPane1.add(f, javax.swing.JDesktopPane.CENTER_ALIGNMENT);
        f.show();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    public void showLogin() {
        java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
        // Get the screen dimensions.
        java.awt.Dimension screen = tk.getScreenSize();
        loginJFrame1 f = new loginJFrame1(this);
        int fw = (int) (screen.getWidth());
        int fh = (int) (screen.getWidth());
        java.awt.Dimension fs = f.getSize();
        int lx = (int) (screen.getWidth() / 2 - fs.getWidth() / 2);
        int ly = (int) (screen.getHeight() / 2 - fs.getHeight() / 2);
        f.setLocation(lx, ly);
        jDesktopPane1.add(f, javax.swing.JDesktopPane.CENTER_ALIGNMENT);
        f.show();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            java.awt.Dimension screensize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();

            try {
                String[] lafs = {
                    "de.javasoft.plaf.synthetica.SyntheticaAluOxideLookAndFeel", //0
                    "de.javasoft.plaf.synthetica.SyntheticaClassyLookAndFeel", //1
                    "de.javasoft.plaf.synthetica.SyntheticaWhiteVisionLookAndFeel",//2
                    "de.javasoft.plaf.synthetica.SyntheticaBlackEyeLookAndFeel",//3
                    "de.javasoft.plaf.synthetica.SyntheticaBlackMoonLookAndFeel",//4
                    "de.javasoft.plaf.synthetica.SyntheticaBlackStarLookAndFeel",//5
                    "de.javasoft.plaf.synthetica.SyntheticaBlueIceLookAndFeel",//6
                    "de.javasoft.plaf.synthetica.SyntheticaBlueLightLookAndFeel",//7
                    "de.javasoft.plaf.synthetica.SyntheticaBlueMoonLookAndFeel",//8
                    "de.javasoft.plaf.synthetica.SyntheticaBlueSteelLookAndFeel",//9
                    "de.javasoft.plaf.synthetica.SyntheticaGreenDreamLookAndFeel",//10
                    "de.javasoft.plaf.synthetica.SyntheticaMauveMetallicLookAndFeel",//11
                    "de.javasoft.plaf.synthetica.SyntheticaSilverMoonLookAndFeel",//12
                    "de.javasoft.plaf.synthetica.SyntheticaSimple2DLookAndFeel", //13
                    "de.javasoft.plaf.synthetica.SyntheticaSkyMetallicLookAndFeel",//14
                    "de.javasoft.plaf.synthetica.SyntheticaOrangeMetallicLookAndFeel"};//15

                System.out.println(System.getProperty("user.dir"));
                String[] li = {"Licensee=Jyloo Software", "LicenseRegistrationNumber=------", "Product=Synthetica", "LicenseType=For internal tests only", "ExpireDate=--.--.----", "MaxVersion=2.999.999"};

                UIManager.put(
                        "Synthetica.license.info", li);
                UIManager.put(
                        "Synthetica.license.key", "E1CBD033-B07718A2-1E181B5F-A78A6DFF-813D8FB4");

                UIManager.setLookAndFeel(
                        lafs[9]);

            } catch (Exception ex) {
                System.out.println("Error :" + ex.toString());
            }

            try {
                MainFrame mf = new MainFrame();

                mf.setSize(screensize.width, screensize.height);
                mf.show();

                //mf.setBackground (new java.awt.Color (253, 153, 255));
            } catch (Exception x) {
                System.out.println(" Exception = " + x.toString());
            }
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void loginSuccess() {
        jMenu2.setEnabled(true);
        jMenuItem3.setEnabled(true);
        jMenuItem1.setEnabled(false);
    }

    public void loginOut() {
        jMenu2.setEnabled(false);
        jMenuItem3.setEnabled(false);
        jMenuItem1.setEnabled(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
